version: "3.8"
services:
  docker-arch-php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm-alpine:dev
    env_file:
      - infrastructure/environment/dev/common.env
      - infrastructure/environment/dev/mariadb.env
      - infrastructure/environment/dev/redis.env
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    links:
      - docker-arch-mariadb
      - docker-arch-redis

  docker-arch-mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: docker-arch
    volumes:
      - ./infrastructure/mariadb/migrate:/docker-entrypoint-initdb.d
      - ./infrastructure/mariadb/confd:/etc/mysql/conf.d
    ports:
      - "3306/tcp"

  docker-arch-redis:
    image: redis
    volumes:
      - ./infrastructure/var/redis:/var/lib/redis
      - ./infrastructure/redis/dev:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  docker-arch-nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./infrastructure/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3699:80"
    links:
      - docker-arch-php