version: "3.7"
services:
  docker-arch-php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm-alpine:dev
    env_file:
      - infrastructure/environment/dev/common.env
      - infrastructure/environment/dev/mariadb.env
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    links:
      - docker-arch-mariadb
      - docker-arch-redis

  docker-arch-mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: docker-arch
    volumes:
      - ./infrastructure/mariadb/migrate:/docker-entrypoint-initdb.d
      - ./infrastructure/mariadb/confd:/etc/mysql/conf.d
    ports:
      - "3306/tcp"

#  docker-arch-redis:
#    image: redis
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_DATABASE: docker-arch
#    volumes:
#      - ./infrastructure/mariadb/migrate:/docker-entrypoint-initdb.d
#      - ./infrastructure/mariadb/confd:/etc/mysql/conf.d
#    ports:
#      - "3306/tcp"

  docker-arch-nginx:
    image: nginx:latest
    ports:
      - "3699:80"
    volumes:
      - .:/var/www/html
      - ./infrastructure/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - docker-arch-php