version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm-alpine:dev
    env_file:
      - infrastructure/environment/dev/common.env
      - infrastructure/environment/dev/mariadb.env
      - infrastructure/environment/dev/redis.env
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    links:
      - mariadb
      - redis

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: arch
      MYSQL_DATABASE: docker_arch
    volumes:
      - ./infrastructure/mariadb/migrate:/docker-entrypoint-initdb.d
      - ./infrastructure/mariadb/confd:/etc/mysql/conf.d
      - ./var/lib/mysql:/var/lib/mysql
    ports:
      - "3306/tcp"

  redis:
    image: redis:latest
    volumes:
      - ./var/lib/redis:/var/lib/redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./infrastructure/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3699:80"
    links:
      - php